### PR TITLE
Minor clarifications / simplification for getting started guide

### PR DESCRIPTION
**Pull request by mjlodge**
Hi,

Just updating the guide to match the actual user email format Github uses, to avoid any potential confusion for newcomers. Also a simpler git command to check the user.email property.

### CODE REVIEW

**Comment by mjlodge** [comment]
Hi, Diffblue has signed the CLA. Is there something I need to do to make the bot recognize that?

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by maoo** [comment]
@cla-bot[bot] check

**Comment by maoo** [comment]
> Hi @finos-admin Diffblue has signed the CLA. Is there something I need to do to make the bot recognize that?

@mjlodge , thanks for the contribution! As this was your first contribution, we had to add you to the list of approved contributors (as per DiffBlue CCLA); now you're into our systems and this PR got re-summoned to pass the CLA checks.

Our CLA Bot also offers the ability to whitelist all authors who sign git commits with a `@diffblue.com` email domain; this would allow the bot to approve all Diffblue PRs, even the first ones, although it would force all Diffblue contributors to set their diffblue email address as `user.email` git config parameter.

Feel free to email help@finos.org if you'd like to enable this feature, and/or you'd like to submit personal info about new FINOS contributors from Diffblue.

Thank you!

**Review by gs-bracej — APPROVED** [review]

**Pull request merged**
