### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by kplus**
The last section in Maven installation page should be
setup legend-studio.

Signed-off-by: Kejia Hu <kejia.hu@codethink.co.uk>

### CODE REVIEW

**Comment by akphi** [comment]
Thank you for your contribution! Could you follow through with the instruction and get CLA approved?

**Comment by kplus** [comment]
> Thank you for your contribution! Could you follow through with the instruction and get CLA approved?

Thanks for your comment. I believe my employer(Codethink Ltd.) should have a CCLA with FINOS in place already. I am just waiting for my corporation email to be added to the agreement.

**Comment by maoo** [comment]
@akphi , thanks for chiming in! I'll apply the changes and re-summon this PR . I'll let you know when it's ready to be merged.

**Comment by maoo** [comment]
@cla-bot[bot] check

**Pull request merged**
