### PR TITLE
Add documentation for installing legend on openshift using helm

### PR DESCRIPTION
**Pull request by zvigrinberg**

### CODE REVIEW

**Comment by krumware** [comment]
Thanks for doing this!
We're not using openshift but deploying into vanilla clusters and picked up the helm for updates. 
How much of this is OCP specific versus standard helm with a different values.yaml?

**Comment by zvigrinberg** [comment]
Hi Colin,
No problem.
This is mainly a  run-book and modified values.yaml (that uses the existing
helm chart)  to enable installing legend on Openshift more easily and
successfully..( already verified on an openshift Cluster).
I've been asked by my colleagues at Redhat( followed by a request from the
finos community ) to help with that one.

Thanks And regards,

Zvi.

**Comment by TheJuanAndOnly99** [comment]
@cla-bot[bot] check

**Comment by TheJuanAndOnly99** [comment]
@cla-bot[bot] check

**Comment by TheJuanAndOnly99** [comment]
@cla-bot[bot] check

**Comment by zvigrinberg** [comment]
@TheJuanAndOnly99 Thanks for fixing the CLA issue!.
@epsstan Can you please review it?? It's the procedure i've shown you on the zoom meeting we had with Josh last week.

**Comment by zvigrinberg** [comment]
@epsstan Can you please take a look and  review it?? Thanks.

**Comment by sauagarwa** [comment]
@zvigrinberg: This helm chart refers to the studio version "0.2.5" which is around 2 years old. Also, docker-compose version  does include other microservices like depot and depot-store. Would it be possible to upgrade the helm chart to use the latest images.?

**Comment by finos-admin** [comment]
This PR is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by zvigrinberg** [comment]
@epsstan Please review as agreed.

**Review by epsstan — APPROVED** [review]

**Pull request merged**
