### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by akphi**

### CODE REVIEW

**Review by MauricioUyaguari — APPROVED** [review]

**Comment by absnarang** [comment]
```
SELECT
    "root"."entityId" AS "entityId",
    "root"."fiscalYear" AS "fiscalYear",
    "root"."env.climate.emissions.ghgScope1Absolute" AS "env.climate.emissions.ghgScope1Absolute",
    "root"."env.climate.emissions.ghgScope1Absolute_unit" AS "env.climate.emissions.ghgScope1Absolute_unit",
    "root"."env.climate.emissions.ghgScope1Absolute.pcafScore" AS "env.climate.emissions.ghgScope1Absolute.pcafScore",
    "root"."env.climate.emissions.ghgScope1Absolute.sourceDescription" AS "env.climate.emissions.ghgScope1Absolute.sourceDescription",
    "root"."env.climate.emissions.ghgScope2LocAbsolute" AS "env.climate.emissions.ghgScope2LocAbsolute",
    "root"."env.climate.emissions.ghgScope2LocAbsolute_unit" AS "env.climate.emissions.ghgScope2LocAbsolute_unit",
    "root"."env.climate.emissions.ghgScope2LocAbsolute.pcafScore" AS "env.climate.emissions.ghgScope2LocAbsolute.pcafScore",
    "root"."env.climate.emissions.ghgScope2LocAbsolute.sourceDescription" AS "env.climate.emissions.ghgScope2LocAbsolute.sourceDescription"
FROM
    service(
        pattern => '/finos/esg/env/climate/getEmissionData',
        project => 'OMNIBUS-51104062',
        groupWorkspace => 'GWS8'

    ) AS "root"
    ```

**Comment by akphi** [comment]
```sh
curl --location 'https://d7nifimeibcde.cloudfront.net/engine/api/sql/v1/execution/executeQueryString?serializationFormat=DEFAULT&client_name=gitlabPAToken' \
--header 'legend-test-pat: PUT_YOUR_PAT_HERE' \
--header 'Content-Type: text/plain' \
--data 'SELECT
    "root"."entityId" AS "entityId",
    "root"."fiscalYear" AS "fiscalYear",
    "root"."env.climate.emissions.ghgScope1Absolute" AS "env.climate.emissions.ghgScope1Absolute",
    "root"."env.climate.emissions.ghgScope1Absolute_unit" AS "env.climate.emissions.ghgScope1Absolute_unit",
    "root"."env.climate.emissions.ghgScope1Absolute.pcafScore" AS "env.climate.emissions.ghgScope1Absolute.pcafScore",
    "root"."env.climate.emissions.ghgScope1Absolute.sourceDescription" AS "env.climate.emissions.ghgScope1Absolute.sourceDescription",
    "root"."env.climate.emissions.ghgScope2LocAbsolute" AS "env.climate.emissions.ghgScope2LocAbsolute",
    "root"."env.climate.emissions.ghgScope2LocAbsolute_unit" AS "env.climate.emissions.ghgScope2LocAbsolute_unit",
    "root"."env.climate.emissions.ghgScope2LocAbsolute.pcafScore" AS "env.climate.emissions.ghgScope2LocAbsolute.pcafScore",
    "root"."env.climate.emissions.ghgScope2LocAbsolute.sourceDescription" AS "env.climate.emissions.ghgScope2LocAbsolute.sourceDescription"
FROM
    service(
        pattern => '\''/finos/esg/env/climate/getEmissionData'\'',
        project => '\''OMNIBUS-51104062'\'',
        groupWorkspace => '\''GWS8'\''

    ) AS "root"'
```

**Comment by akphi** [comment]
```python
# Below is a demonstration of how to use pylegend lib service frame taking esgEmissionsData service.
# It assumes Legend engine running on localhost at 6300 port. There is no Auth here on local
# you can grab pylegend from pip
# pip install pylegend

import pylegend
from pylegend.core.request.auth import BearerAuthScheme

tds_client = pylegend.LegendApiTdsClient(
    legend_client=pylegend.LegendClient(
        host="d7nifimeibcde.cloudfront.net",
        port=80,
        path_prefix="/engine/api",
        auth_scheme=BearerAuthScheme('legend-test-pat', '__YOUR_PAT__'),
        secure_http=False
    )
)

frame = tds_client.legend_service_frame(
    service_pattern="/finos/esg/env/climate/getEmissionData",
    project_coordinates=pylegend.GroupWorkspaceProjectCoordinates(
        project_id="OMNIBUS-51104062",
        group_workspace="GWS8",
    )
)

df = frame.execute_frame_to_pandas_df()
print(df)

dfteststring = frame.to_sql_query()
print(dfteststring)
```

**Comment by akphi** [comment]
```python
# Below is a demonstration of how to use pylegend lib service frame taking esgEmissionsData service.
# It assumes Legend engine running on localhost at 6300 port. There is no Auth here on local
# you can grab pylegend from pip
# pip install pylegend

import pylegend # version >= 0.3.0
from pylegend.core.request.auth import HeaderTokenAuthScheme

tds_client = pylegend.LegendApiTdsClient(
    legend_client=pylegend.LegendClient(
        host="d7nifimeibcde.cloudfront.net",
        port=80,
        path_prefix="/engine/api",
        auth_scheme=HeaderTokenAuthScheme(header_name='legend-test-pat', token_provider=lambda: '________YOUR_TOKEN_HERE________'),
        secure_http=False
    )
)

frame = tds_client.legend_service_frame(
    service_pattern="/finos/esg/env/climate/getEmissionData",
    project_coordinates=pylegend.GroupWorkspaceProjectCoordinates(
        project_id="OMNIBUS-51104062",
        group_workspace="GWS8",
    )
)

df = frame.execute_frame_to_pandas_df()
print(df)

dfteststring = frame.to_sql_query()
print(dfteststring)
```

**Comment by akphi** [comment]
Try this URL for testing
https://dla3uc9je36km.cloudfront.net/studio/edit/OMNIBUS-51104062/groupWorkspace/epsstan-ws2/

**Comment by absnarang** [comment]
https://dla3uc9je36km.cloudfront.net/studio/

**Comment by absnarang** [comment]
from urllib.request import Request, urlopen

req = Request('[https://dla3uc9je36km.cloudfront.net/engine/api/sql/v1/execution/executeQueryString?serializationFormat=DEFAULT&client_name=gitlabPAToken](https://urldefense.com/v3/__https:/dla3uc9je36km.cloudfront.net/engine/api/sql/v1/execution/executeQueryString?serializationFormat=DEFAULT&client_name=gitlabPAToken__;!!O2kDR7mm-zSJ!pbiJYrXd4tur653-y4S_VriQaBDpomRrq-lwEDz60Yjpz-B5zlduMLXXWSRW2f08j5oimgDxBmHNpLiH0L2ygBdI$)')

req.add_header('legend-test-pat', my_pat )

req.add_header('Content-Type', 'text/plain' )

req.data = b"""SELECT * FROM service( pattern => '/finos/esg/pos/getJSONPortfolioReport', project => 'OMNIBUS-51104062', groupWorkspace => 'marrid' ) AS "root" """

#req.data = b"""SELECT * FROM service( pattern => '/finos/esg/env/climate/getEmissionData', project => 'OMNIBUS-51104062', groupWorkspace => 'marrid' ) AS "root" """

string_result = urlopen(req).read()

string_result

**Comment by akphi** [comment]
/engine/api/server/v1/info
/sdlc/api/server/info

**Comment by absnarang** [comment]
{"function":{"_type":"lambda","body":[{"_type":"func","function":"serialize","parameters":[{"_type":"func","function":"graphFetch","parameters":[{"_type":"func","function":"take","parameters":[{"_type":"func","function":"filter","parameters":[{"_type":"func","function":"getAll","parameters":[{"_type":"packageableElementPtr","fullPath":"FinOS::ESG::domain::ESGMetricsPortfolio"}]},{"_type":"lambda","body":[{"_type":"func","function":"equal","parameters":[{"_type":"property","parameters":[{"_type":"var","name":"x"}],"property":"entityType"},{"_type":"string","value":"PORTFOLIO"}]}],"parameters":[{"_type":"var","name":"x"}]}]},{"_type":"integer","value":1000}]},{"_type":"classInstance","multiplicity":{"lowerBound":1,"upperBound":1},"type":"rootGraphFetchTree","value":{"_type":"rootGraphFetchTree","class":"FinOS::ESG::domain::ESGMetricsPortfolio","subTrees":[{"_type":"propertyGraphFetchTree","parameters":[],"property":"portfolioId","subTrees":[],"subTypeTrees":[]},{"_type":"propertyGraphFetchTree","parameters":[],"property":"fiscalYear","subTrees":[],"subTypeTrees":[]},{"_type":"propertyGraphFetchTree","parameters":[],"property":"env","subTrees":[{"_type":"propertyGraphFetchTree","parameters":[],"property":"climate","subTrees":[{"_type":"propertyGraphFetchTree","parameters":[],"property":"emissions","subTrees":[{"_type":"propertyGraphFetchTree","parameters":[],"property":"ghgScope1Absolute","subTrees":[{"_type":"propertyGraphFetchTree","parameters":[],"property":"value","subTrees":[],"subTypeTrees":[]},{"_type":"propertyGraphFetchTree","parameters":[],"property":"sourceDescription","subTrees":[],"subTypeTrees":[]}],"subTypeTrees":[]},{"_type":"propertyGraphFetchTree","parameters":[],"property":"ghgScope2LocAbsolute","subTrees":[{"_type":"propertyGraphFetchTree","parameters":[],"property":"value","subTrees":[],"subTypeTrees":[]},{"_type":"propertyGraphFetchTree","parameters":[],"property":"sourceDescription","subTrees":[],"subTypeTrees":[]}],"subTypeTrees":[]}],"subTypeTrees":[]}],"subTypeTrees":[]}],"subTypeTrees":[]}],"subTypeTrees":[]}}]},{"_type":"classInstance","multiplicity":{"lowerBound":1,"upperBound":1},"type":"rootGraphFetchTree","value":{"_type":"rootGraphFetchTree","class":"FinOS::ESG::domain::ESGMetricsPortfolio","subTrees":[{"_type":"propertyGraphFetchTree","parameters":[],"property":"portfolioId","subTrees":[],"subTypeTrees":[]},{"_type":"propertyGraphFetchTree","parameters":[],"property":"fiscalYear","subTrees":[],"subTypeTrees":[]},{"_type":"propertyGraphFetchTree","parameters":[],"property":"env","subTrees":[{"_type":"propertyGraphFetchTree","parameters":[],"property":"climate","subTrees":[{"_type":"propertyGraphFetchTree","parameters":[],"property":"emissions","subTrees":[{"_type":"propertyGraphFetchTree","parameters":[],"property":"ghgScope1Absolute","subTrees":[{"_type":"propertyGraphFetchTree","parameters":[],"property":"value","subTrees":[],"subTypeTrees":[]},{"_type":"propertyGraphFetchTree","parameters":[],"property":"sourceDescription","subTrees":[],"subTypeTrees":[]}],"subTypeTrees":[]},{"_type":"propertyGraphFetchTree","parameters":[],"property":"ghgScope2LocAbsolute","subTrees":[{"_type":"propertyGraphFetchTree","parameters":[],"property":"value","subTrees":[],"subTypeTrees":[]},{"_type":"propertyGraphFetchTree","parameters":[],"property":"sourceDescription","subTrees":[],"subTypeTrees":[]}],"subTypeTrees":[]}],"subTypeTrees":[]}],"subTypeTrees":[]}],"subTypeTrees":[]}],"subTypeTrees":[]}}]}],"parameters":[]},"mapping":"FinOS::ESG::mapping::CuratedESGMapping","model":{"_type":"pointer","sdlcInfo":{"_type":"alloy","baseVersion":"latest","version":"0.1.3","groupId":"org.finos.legend.esg","artifactId":"esg-reg-reporting","packageableElementPointers":[]}},"runtime":{"_type":"runtimePointer","runtime":"FinOS::ESG::connection::H2ESGRuntime"},"context":{"_type":"BaseExecutionContext","queryTimeOutInSeconds":null,"enableConstraints":true}}

**Comment by absnarang** [comment]
|FinOS::ESG::domain::ESGMetricsPortfolio.all()->filter(
  x|$x.entityType == 'PORTFOLIO'
)->graphFetch(
  #{
    FinOS::ESG::domain::ESGMetricsPortfolio{
      portfolioId,
      fiscalYear,
      env{
        climate{
          emissions{
            ghgScope1Absolute{
              value,
              sourceDescription
            },
            ghgScope2LocAbsolute{
              value,
              sourceDescription
            }
          }
        }
      }
    }
  }#
)->serialize(
  #{
    FinOS::ESG::domain::ESGMetricsPortfolio{
      portfolioId,
      fiscalYear,
      env{
        climate{
          emissions{
            ghgScope1Absolute{
              value,
              sourceDescription
            },
            ghgScope2LocAbsolute{
              value,
              sourceDescription
            }
          }
        }
      }
    }
  }#
)

**Comment by absnarang** [comment]
https://dla3uc9je36km.cloudfront.net/studio/edit/OMNIBUS-51104062/groupWorkspace/gfjson/


/finos/esg/pos/getJSONPortfolioReport

**Comment by akphi** [comment]
@absnarang 
```python
GITLAB_PRIVATE_ACCESS_TOKEN = "____YOUR_PRIVATE_ACCESS_TOKEN____"
PROJECT_ID = "OMNIBUS-51104062"
GROUP_WORKSPACE = "gfjson"
SERVICE_PATH = "FinOS::ESG::services::pos::getJSONPortfolioReport"
RUNTIME_PATH = ""  # if error occured when runtime is not specified as an runtime pointer in the service

SDLC_BASE_URL = "https://dla3uc9je36km.cloudfront.net/sdlc/api"
ENGINE_BASE_URL = "https://dla3uc9je36km.cloudfront.net/engine/api"

# ------------------------------- MAIN --------------------------------

import requests
from pylegend.core.request.auth import HeaderTokenAuth

# get the service
service_entity_fetch_result = requests.get(
    SDLC_BASE_URL
    + "/projects/{projectId}/groupWorkspaces/{workspace}/entities/{entityPath}".format(
        projectId=PROJECT_ID, workspace=GROUP_WORKSPACE, entityPath=SERVICE_PATH
    ),
    auth=HeaderTokenAuth(
        header_name="legend-test-pat",
        token_provider=lambda: GITLAB_PRIVATE_ACCESS_TOKEN,
    ),
)
# extract mapping, runtime, and the function
service_element_protocol = service_entity_fetch_result.json()["content"]
mappingPath = service_element_protocol["execution"]["mapping"]
runtimePath = ""
try:
    runtimePath = service_element_protocol["execution"]["runtime"]["runtime"]
except:
    # if runtime pointer is not specified, fallback to use the custom runtime path
    runtimePath = RUNTIME_PATH
function_protocol = service_element_protocol["execution"]["func"]
pmcd_fetch_result = requests.get(
    SDLC_BASE_URL
    + "/projects/{projectId}/groupWorkspaces/{workspace}/pureModelContextData".format(
        projectId=PROJECT_ID, workspace=GROUP_WORKSPACE
    ),
    auth=HeaderTokenAuth(
        header_name="legend-test-pat",
        token_provider=lambda: GITLAB_PRIVATE_ACCESS_TOKEN,
    ),
)
# get PMCD (if engine supports SDLC workspace pointer, we don't need to do this)
# See https://github.com/finos/legend-engine/pull/2437
pmcd = pmcd_fetch_result.json()
# execute
execution_result = requests.post(
    ENGINE_BASE_URL + "/pure/v1/execution/execute",
    json={
        "function": function_protocol,
        "mapping": mappingPath,
        "model": pmcd,
        "runtime": {
            "_type": "runtimePointer",
            "runtime": runtimePath,
        },
        "context": {
            "_type": "BaseExecutionContext",
            "queryTimeOutInSeconds": None,
            "enableConstraints": True,
        },
    },
    auth=HeaderTokenAuth(
        header_name="legend-test-pat",
        token_provider=lambda: GITLAB_PRIVATE_ACCESS_TOKEN,
    ),
)
print(execution_result.text)
```

**Comment by absnarang** [comment]
SELECT
    "root"."portfolioId" AS "portfolioId",
    "root"."portfolioDate" AS "portfolioDate",
    "root"."fiscalYear" AS "fiscalYear",
    "root"."portfolioGhgScope1Emissions" AS "portfolioGhgScope1Emissions"
FROM
    service(
        pattern => '/finos/esg/env/climate/getPortfolioEmissions',
        project => 'OMNIBUS-51104062',
        groupWorkspace => 'GWS9'
    ) AS "root"

**Comment by akphi** [comment]
script to run backup omnibus (with SDLC using file-system)

```sh
curl https://legend.finos.org/omnibus/start.esg.sh | bash
curl https://legend.finos.org/omnibus/start.example-esg.latest.sh | bash
```

**Pull request merged**
