### PR TITLE
Add showcase placeholders

### PR DESCRIPTION
**Pull request by agitana**

### CODE REVIEW

**Review by akphi — CHANGES_REQUESTED** [review]
Thank you for the work! Just a few feedbacks:

1. Let's organize slightly differently, under `External Formats`, we should have `Avro, JSON Schema, etc.` as top-levels (just like for Stores, we have `Model Store, Relational, etc.`, then under each, we have `Binding`, `Externalize`, etc.
2. Let's name all the folders in [Title case](https://en.wikipedia.org/wiki/Title_case) as this will be what we display in the showcase explorer (i.e. we preserve the casing when displaying there so let's make them look nice here)
3. Let's remove `tags` for all of the `info.md` -- this field is not used so let's just remove it (if possible, for my dummy example under /Stores, can you help me remove them? - thanks!)
4. Let's at least give a title for each `info.md`, these will be displayed in the showcase explorer

**Comment by agitana** [comment]
Thank you @akphi replying in-line:

> Thank you for the work! Just a few feedbacks:
> 
> 1. Let's organize slightly differently, under `External Formats`, we should have `Avro, JSON Schema, etc.` as top-levels (just like for Stores, we have `Model Store, Relational, etc.`, then under each, we have `Binding`, `Externalize`, etc.

Addressed, let me know if further changes required. I did leave "query editor", "service editor" and "service test editor" directly nested under "external formats", let me know these folders should be within each one of the format-specific folders.
 
> 2. Let's name all the folders in [Title case](https://en.wikipedia.org/wiki/Title_case) as this will be what we display in the showcase explorer (i.e. we preserve the casing when displaying there so let's make them look nice here)

Done.
> 3. Let's remove `tags` for all of the `info.md` -- this field is not used so let's just remove it (if possible, for my dummy example under /Stores, can you help me remove them? - thanks!)

Done.
> 4. Let's at least give a title for each `info.md`, these will be displayed in the showcase explorer

WDYT of requesting this as part of the exercise of building out the actual showcases?

**Comment by akphi** [comment]
> Addressed, let me know if further changes required. I did leave "query editor", "service editor" and "service test editor" directly nested under "external formats", let me know these folders should be within each one of the format-specific folders.

I don't think they should be, also why do we have both "vnd.google.protobuf" and "Protofbuf", are they meant to be different?

**Comment by agitana** [comment]
> > Addressed, let me know if further changes required. I did leave "query editor", "service editor" and "service test editor" directly nested under "external formats", let me know these folders should be within each one of the format-specific folders.
> 
> I don't think they should be, also why do we have both "vnd.google.protobuf" and "Protofbuf", are they meant to be different?

Removed protobuf duplicate

**Pull request merged**
