### PR TITLE
Added Legend Helm Chart with Remote Gitlab

### PR DESCRIPTION
**Pull request by naeemarsalan**
Converted Docker-Compose to Helm chart to run CNCF Kubernetes Cluster.

### CODE REVIEW

**Comment by maoo** [comment]
Hi @naeemarsalan , thanks so much for this contribution; I haven't tested it, but looking at it, I can confirm that this is something that the community have been waiting for since Legend was open sourced to FINOS.

As maintainer of a Legend instance - legend.finos.org/studio - I'm sure that this Helm chart will make my life much easier!

We're now working with SUSE to sign the a Corporate CLA with FINOS and eventually allow this PR to be merged (will keep you posted), but in the meantime, I'd suggest the community and the GS team to review this work.

I love what you've done on the `README.md`, I'll make some time next week to give it a try.

**Comment by maoo** [comment]
@cla-bot[bot] check

**Comment by maoo** [comment]
Hi @naeemarsalan ! I've tested the Helm chart using Minikube, I documented my journey on https://gist.github.com/maoo/3f8f22c6d22c3e97cbb6bdd3661028d3

The relevant changes I made were:
- Replacing `nip.io` with NGrok, as we need to have those ports publicly accessible, in order for the callbacks to work
- Updating Docker image versions to the latest ones

I see that the callbacks are working, which is great, but Studio is failing with the following error:
```
BrowserConsole.ts:45 [1633990792658] APPLICATION_FAILURE : Failed to load Legend application
StudioConfig.ts:223 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'url')
    at new t_ (StudioConfig.ts:223)
    at wF.configureApplication (LegendStudio.tsx:73)
    at wF.fetchApplicationConfiguration (LegendApplication.tsx:227)
    at async wF.start (LegendApplication.tsx:247)
```

Is this the same error you're experiencing, or you're able to use Studio?

@akphi - I remember we stumbled on this in the past? It seems to be an issue in the config files, but I couldn't find anything wrong on https://github.com/naeemarsalan/legend/blob/feature/helm-chart-installer/installers/helm/templates/studio-configmap.yaml . Any ideas?

/cc @epsstan

**Comment by maoo** [comment]
I actually got it working with Studio version `0.2.56`, pretty cool!

Screenshot 2021-10-12 at 00 52 56

I haven't run a deep test, but I think this is a great starting point!

**Comment by finos-admin** [comment]
This PR is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by finos-admin** [comment]
This PR was closed because it has been inactive for 35 days. Please re-open if this PR is still relevant.

**Pull request closed without merging**
