### PR TITLE
update showcase tree structure

### PR DESCRIPTION
**Pull request by agitana**

### CODE REVIEW

**Comment by MauricioUyaguari** [comment]
I don't think we need subfolders under `Build a data model`. 
I think for this we should have one or 2 showcases with a detailed usage of Class, Associations, Enum and a Diagram. 
If we need to do a further split down we could in the future but I think for now thats fine.

**Comment by MauricioUyaguari** [comment]
Lets remove the serializable folder please.

**Comment by MauricioUyaguari** [comment]
text elements don't really interact with the model. we can just rename that folder to 
`Use text element`

**Comment by MauricioUyaguari** [comment]
For now external format is fine, we should do another walkthrough. As
Basically we should probably have it something like
- External Format
  - Types
  - Writing Internalize Func (Reading External Format)
  - Writing Externalize Func (Writing to External Format)

**Comment by agitana** [comment]
thanks @MauricioUyaguari actioned your feedback can you please review?

**Review by MauricioUyaguari — APPROVED** [review]

**Pull request merged**
